apiVersion: batch/v1
kind: CronJob
metadata:
  name: disk-usage
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: disk-check
            image: busybox
            command:
            - /bin/sh
            - -c
            - "df -h"
